---
name: Dependency Scanning (SCA)

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_tag:
        description: "Full image tag to scan"
        required: true
        type: string
      project_name:
        description: "Name of the project"
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history for accurate analysis

      - name: Download Maven Target
        uses: actions/download-artifact@v7
        with:
          name: maven-target
          path: target

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --maven-aggregate-project
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: ./snyk.sarif

      - name: Check if Snyk SARIF file exists
        run: ls -la ./snyk.sarif

  vulnerability_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project_name }}:${{ github.run_number }}

      - name: Debug - List pulled images
        run: docker images

      - name: Run Trivy vulnerability scanner (SARIF)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project_name }}:${{ github.run_number }}
          format: sarif
          output: trivy-results.sarif
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
          limit-severity-for-sarif: true
        continue-on-error: true

      - name: Debug - Check Trivy SARIF file
        run: |
          if [ -f trivy-results.sarif ]; then
            echo "Trivy SARIF file exists.";
            ls -la trivy-results.sarif
            head -n 20 trivy-results.sarif || echo "(file is empty or invalid)"
            jq '.' trivy-results.sarif || echo "(not valid JSON)"
          else
            echo "Trivy SARIF file NOT created.";
            echo "Trivy scan may have failed.";
          fi

      - name: Upload Trivy SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-results.sarif
