---
name: Dependency Scanning (SCA)

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_tag:
        description: "Full image tag to scan"
        required: true
        type: string
      project_name:
        description: "Name of the project"
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate analysis

      - name: Download Maven Target
        uses: actions/download-artifact@v4
        with:
          name: maven-target

      - name: Install Snyk CLI
        uses: snyk/actions/setup@v3

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --maven-aggregate-project
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Check if Snyk SARIF file exists
        run: ls -la ./snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./snyk.sarif

  vulnerability_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project_name }}:${{ github.run_number }}

      - name: Debug Trivy Scan
        run: |
          echo "Attempting to scan image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project_name }}:${{ github.run_number }}"
          docker images
          trivy image --format sarif --output trivy-results.sarif --ignore-unfixed --vuln-type os,library --severity CRITICAL,HIGH ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project_name }}:${{ github.run_number }} || echo "Trivy scan failed"

      - name: Run Trivy vulnerability scanner (SARIF)
        uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.project_name }}:${{ github.run_number }}
          format: sarif
          output: trivy-results.sarif
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Check if Trivy SARIF file exists
        run: ls -la ./trivy-results.sarif

      - name: Upload Trivy SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2.22.3
        with:
          sarif_file: ./trivy-results.sarif
